d/t/control, d/t/smoke-lxc: retry service restart and skip test if failing; Was flaky on some release/architectures (LP: #1899180)
Signed-off-by: Christian Ehrhardt <christian.ehrhardt@canonical.com>

diff --git a/debian/tests/smoke-lxc b/debian/tests/smoke-lxc
--- a/debian/tests/smoke-lxc
+++ b/debian/tests/smoke-lxc
@@ -36,6 +36,18 @@ check_domain()
     return $rc
 }
 
+try_restart_libvirtd()
+{
+    for _ in $(seq 10); do
+        systemctl restart libvirtd && return
+        sleep 2s
+    done
+    # This turned out to be flaky, non reproducible outside of LP-infra and
+    # is not what we want to test, Skip the test in this case
+    echo "Restart failed while checking for container-survival-through restart - skipping".
+    exit 77
+}
+
 trap cleanup EXIT
 
 set -x
@@ -51,7 +63,7 @@ virsh start ${DOMAIN}
 grep -qs "starting up" /var/log/libvirt/lxc/sl.log
 try_check_domain
 # Make sure a restart doesn't termiante the domain
-systemctl restart libvirtd
+try_restart_libvirtd
 try_check_domain
 virsh destroy ${DOMAIN} || true
 virsh undefine ${DOMAIN}
