0.4.2-5ubuntu1 (patches unapplied)
Imported using git-ubuntu import.

diff --git a/debian/libvirt-bin.postinst b/debian/libvirt-bin.postinst
--- a/debian/libvirt-bin.postinst
+++ b/debian/libvirt-bin.postinst
@@ -1,13 +1,44 @@
-#! /bin/sh
+#!/bin/sh
+# postinst script for libvirt-bin
+#
+# see: dh_installdeb(1)
 
 set -e
 
-# add the libvirtd group
-if ! getent group libvirtd > /dev/null 2>&1
-then
-        addgroup --system libvirtd
-fi
+# summary of how this script can be called:
+#        * <postinst> `configure' <most-recently-configured-version>
+#        * <old-postinst> `abort-upgrade' <new version>
+#        * <conflictor's-postinst> `abort-remove' `in-favour' <package>
+#          <new-version>
+#        * <postinst> `abort-remove'
+#        * <deconfigured's-postinst> `abort-deconfigure' `in-favour'
+#          <failed-install-package> <version> `removing'
+#          <conflicting-package> <version>
+# for details, see http://www.debian.org/doc/debian-policy/ or
+# the debian-policy package
+
+
+case "$1" in
+    configure)
+    	if ! getent group libvirt >/dev/null; then
+    		addgroup --system libvirtd
+	fi
+    ;;
+
+    abort-upgrade|abort-remove|abort-deconfigure)
+    ;;
+
+    *)
+        echo "postinst called with unknown argument \`$1'" >&2
+        exit 1
+    ;;
+esac
+
+# dh_installdeb will replace this with shell code automatically
+# generated by other debhelper scripts.
 
 #DEBHELPER#
 
 exit 0
+
+
