d/rules, d/libvirt-daemon-system.{postinst,prerm}: never stop system services and sockets (LP: #1959054)
TL;DR:
- it is a mess, a lot of discussions and bugs to read for full awareness
- since transitions need libvirt soon we upload it with a mitigation now
- it is expected that debhelper in jammy is fixed and we can drop this
  before release
- long term discussion how to deal with it in the salsa PR

Due to debhelper bug 994204 on upgrades guests are shut down
(libvirt-guests.service) or even crash (virtlogd.service) because those
services are restarted.

Until that bug is resolved in debhelper we need to take over the
handling of those services ourselves.

References:
- https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=994204
- https://bugs.launchpad.net/ubuntu/+source/debhelper/+bug/1959054
- https://salsa.debian.org/utopia-team/dbus/-/commit/4c5195a13c69364dce50063afac368930ec75c91

Submitted to Debian via:
https://salsa.debian.org/libvirt-team/libvirt/-/merge_requests/132

The initial version of this was based on the dbus handling of it, but
it turns out that --no-stop-on-upgrade --no-start leaves a stop command
in prerm and thereby we'd have them stopped twice.

Auto added section is identical:
if [ -z "${DPKG_ROOT:-}" ] && [ "$1" = remove ] && [ -d /run/systemd/system ] ; then
        deb-systemd-invoke stop 'libvirt-guests.service' 'virtlockd.service' 'virtlogd.service' >/dev/null || true
fi

Remove that duplicate that we added before following dbus.

It turns out also nowadays restarting the sockets is dangerous.
  $ deb-systemd-invoke restart 'virtlogd.socket'
or
  $ systemctl restart virtlogd.socket
no more complain about being unable to restart for the service being running.
Instead they do restart the service, which makes our restarting of sockets
again kill virtlogd for example.

Therefore we also can not leave the system-services sockets to debhelper
as they would be restarted despite --no-stop-on-upgrade and thereby
restart the related services breaking guests.

As suggested on the Debian PR this removes the remaining debhelper calls
for our system services and sockets.

The remaining little bit it did for us in postinst/postrm is
added directly to these maintainer script now in the non-restart
way that we need.

Signed-off-by: Christian Ehrhardt <christian.ehrhardt@canonical.com>

diff --git a/debian/libvirt-daemon-system.postinst b/debian/libvirt-daemon-system.postinst
--- a/debian/libvirt-daemon-system.postinst
+++ b/debian/libvirt-daemon-system.postinst
@@ -299,4 +299,39 @@ if [ "$1" = "configure" ]; then
     fi
 fi
 
+# We start these units ourselves rather than letting debhelper
+# take responsibility. This is to stop debhelper from ever restarting these,
+# which versions since 13.4 cannot be prevented from doing, except with
+# --no-start
+# https://bugs.debian.org/994204
+if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
+
+    for unit in virtlogd.service virtlockd.service libvirt-guests.service virtlogd.socket virtlogd-admin.socket virtlockd.socket virtlockd-admin.socket; do
+        # This will only remove masks created by d-s-h on package removal.
+        deb-systemd-helper unmask "$unit" >/dev/null || true
+        # was-enabled defaults to true, so new installations run enable.
+        if deb-systemd-helper --quiet was-enabled "$unit"; then
+                # Enables the unit on first installation, creates new
+                # symlinks on upgrades if the unit file has changed.
+                deb-systemd-helper enable "$unit" >/dev/null || true
+        else
+                # Update the statefile to add new symlinks (if any), which need to be
+                # cleaned up on purge. Also remove old symlinks.
+                deb-systemd-helper update-state "$unit" >/dev/null || true
+        fi
+    done
+
+    # Of these units virtlogd and virtlockd services have socket files and are fine
+    # without being started explicitly at this stage, but having debhelper
+    # start the sockets will make them re-started on upgrade/reinstall which will
+    # nowadays in turn also restart the services which we do not want to happen.
+    if [ -z "${DPKG_ROOT:-}" ]; then
+        if [ -d /run/systemd/system ]; then
+            systemctl --system daemon-reload >/dev/null || true
+            deb-systemd-invoke start 'libvirt-guests.service' >/dev/null || true
+            deb-systemd-invoke start 'virtlogd.socket' 'virtlogd-admin.socket' 'virtlockd.socket' 'virtlockd-admin.socket' >/dev/null || true
+        fi
+    fi
+fi
+
 exit 0
