6.9.0-2 (patches unapplied)
Imported using git-ubuntu import.

diff --git a/debian/libvirt-daemon-system.postrm b/debian/libvirt-daemon-system.postrm
--- a/debian/libvirt-daemon-system.postrm
+++ b/debian/libvirt-daemon-system.postrm
@@ -1,7 +1,4 @@
 #!/bin/sh
-# postrm script for libvirt-daemon-system
-#
-# see: dh_installdeb(1)
 
 set -e
 
@@ -18,6 +15,56 @@ set -e
 # for details, see https://www.debian.org/doc/debian-policy/ or
 # the debian-policy package
 
+abort_conffile_transfer() {
+    local conffile="$1"
+    local lastver="$2"
+    local pkgfrom="$3"
+    local pkgto="$4"
+
+    if [ "$5" != "--" ]; then
+        echo "abort_conffile_transfer called with the wrong number of arguments" >&2
+        return 1
+    fi
+    for _ in $(seq 1 5); do
+        shift
+    done
+
+    # If we were installing from scratch or upgrading from a new enough version
+    # when the error occurred, then no transfer was in progress and we don't
+    # need to rollback any changes
+    if [ -z "$2" ] || dpkg --compare-versions -- "$2" gt "$lastver"; then
+        return 0
+    fi
+
+    # If the conffile was being transferred, return it to its original location
+    if [ -e "$conffile.dpkg-transfer" ]; then
+        mv -f "$conffile.dpkg-transfer" "$conffile"
+    fi
+
+    # Clean up additional state
+    rm -f "$conffile.dpkg-disappear"
+}
+
+NWFILTERS="
+    allow-arp
+    allow-dhcp-server
+    allow-dhcp
+    allow-incoming-ipv4
+    allow-ipv4
+    clean-traffic-gateway
+    clean-traffic
+    no-arp-ip-spoofing
+    no-arp-mac-spoofing
+    no-arp-spoofing
+    no-ip-multicast
+    no-ip-spoofing
+    no-mac-broadcast
+    no-mac-spoofing
+    no-other-l2-traffic
+    no-other-rarp-traffic
+    qemu-announce-self-rarp
+    qemu-announce-self
+"
 
 case "$1" in
     purge)
@@ -37,7 +84,7 @@ case "$1" in
         rm -rf /var/log/libvirt \
                /var/cache/libvirt/qemu/capabilities
 
-        # Clean up created dirs if existend and emtpy, they contain precious
+        # Clean up created dirs if existent and empty, they contain precious
         # data otherwise
         for dir in /var/lib/libvirt/qemu/save \
                    /var/lib/libvirt/qemu/snapshot \
@@ -51,17 +98,49 @@ case "$1" in
                    /var/cache/libvirt/qemu; do
             [ ! -d $dir ] || rmdir --ignore-fail-on-non-empty $dir
         done
-        ;;
-    remove|upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)
-        ;;
+    ;;
+
+    abort-install|abort-upgrade)
+        abort_conffile_transfer \
+            "/etc/libvirt/qemu/networks/default.xml" \
+            "6.9.0-2~" \
+            "libvirt-daemon-system" \
+            "libvirt-daemon-config-network" \
+            -- \
+            "$@"
+        for nwfilter in $NWFILTERS; do
+            abort_conffile_transfer \
+                "/etc/libvirt/nwfilter/$nwfilter.xml" \
+                "6.9.0-2~" \
+                "libvirt-daemon-system" \
+                "libvirt-daemon-config-nwfilter" \
+                -- \
+                "$@"
+        done
+
+        # dh_apparmor can't work with dir/file profile filenames yet (#979500)
+        ABSTRACTIONS_DIR="/etc/apparmor.d/abstractions"
+        LOCAL_ABSTRACTIONS_DIR="/etc/apparmor.d/local/abstractions"
+        LIBVIRT_ABSTRACTIONS="libvirt-lxc libvirt-qemu"
+        for name in $LIBVIRT_ABSTRACTIONS; do
+            abstraction="$ABSTRACTIONS_DIR/$name"
+            local_abstraction="$LOCAL_ABSTRACTIONS_DIR/$name"
+
+            if [ ! -e "$abstraction" ] ; then
+                rm -f "$local_abstraction"
+                rmdir --ignore-fail-on-non-empty "$LOCAL_ABSTRACTIONS_DIR" 2>/dev/null
+            fi
+        done
+    ;;
+
+    remove|upgrade|failed-upgrade|disappear)
+    ;;
+
     *)
         echo "postrm called with unknown argument \`$1'" >&2
         exit 1
-        ;;
+    ;;
 esac
-
-# dh_installdeb will replace this with shell code automatically
-# generated by other debhelper scripts.
 
 #DEBHELPER#
 
