1.3.1-1ubuntu3 (patches unapplied)
Imported using git-ubuntu import.

diff --git a/debian/libvirt-bin.virtlockd.init b/debian/libvirt-bin.virtlockd.init
--- a/debian/libvirt-bin.virtlockd.init
+++ b/debian/libvirt-bin.virtlockd.init
@@ -1,98 +1,163 @@
 #!/bin/sh
-
-# the following is the LSB init header see
-# http://refspecs.linuxfoundation.org/LSB_5.0.0/LSB-Core-generic/LSB-Core-generic/initscrcomconv.html
+#
+# Init script for virtlockd
+#
+# (c) 2015 Guido Guenther <agx@sigxcpu.org>
+# based on the skeletons that comes with dh_make
 #
 ### BEGIN INIT INFO
-# Provides: virtlockd
-# Default-Start: 2 3 4 5
-# Default-Stop: 0 1 6
-# Required-Start: $local_fs $remote_fs $syslog
-# Required-Stop: $local_fs $remote_fs $syslog
-# Should-Start:
-# Should-Stop:
+# Provides:          virtlockd
+# Required-Start:    $local_fs $remote_fs $syslog
+# Required-Stop:     $local_fs $remote_fs $syslog
+# Default-Start:     2 3 4 5
+# Default-Stop:      0 1 6
 # Short-Description: virtual machine lock manager
 # Description: This is a daemon for managing locks
 #              on virtual machine disk images
 ### END INIT INFO
 
-# the following is chkconfig init header
-#
-# virtlockd:   virtual machine lock manager
-#
-# chkconfig: 345 96 04
-# description:  This is a daemon for managing locks \
-#               on virtual machine disk images
-#
-# processname: virtlockd
-# pidfile: /var/run/virtlockd.pid
-#
+PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
+export PATH
+DAEMON=/usr/sbin/virtlockd
+NAME=virtlockd
+DESC="libvirt virtual machine lock manager"
 
-# Source function library.
+test -x $DAEMON || exit 0
 . /lib/lsb/init-functions
 
-SERVICE=virtlockd
-PROCESS=virtlockd
-PIDFILE=/var/run/$SERVICE.pid
+PIDFILE=/var/run/$NAME.pid
+DODTIME=1                   # Time to wait for the server to die, in seconds
 
-VIRTLOCKD_ARGS=
+# Include libvirtd defaults if available
+if [ -f /etc/default/virtlockd ] ; then
+	. /etc/default/virtlockd
+fi
 
-test -f /etc/default/virtlockd && . /etc/default/virtlockd
-
-RETVAL=0
-
-start() {
-    echo -n "Starting $SERVICE daemon: "
-    daemon --pidfile $PIDFILE --check $SERVICE $PROCESS --daemon $VIRTLOCKD_ARGS
-    RETVAL=$?
-    echo
-    [ $RETVAL -eq 0 ] && touch /var/lock/subsys/$SERVICE
+running_pid()
+{
+    # Check if a given process pid's cmdline matches a given name
+    pid=$1
+    name=$2
+    [ -z "$pid" ] && return 1
+    [ ! -d /proc/$pid ] &&  return 1
+    cmd=`cat /proc/$pid/cmdline | tr "\000" "\n"|head -n 1 |cut -d : -f 1`
+    # Is this the expected child?
+    [ "$cmd" != "$name" ] &&  return 1
+    return 0
 }
 
-stop() {
-    echo -n "Stopping $SERVICE daemon: "
+running()
+{
+# Check if the process is running looking at /proc
+# (works for all users)
+    # No pidfile, probably no daemon present
+    [ ! -f "$PIDFILE" ] && return 1
+    # Obtain the pid and check it against the binary name
+    pid=`cat $PIDFILE`
+    running_pid $pid $DAEMON || return 1
+    return 0
+}
 
-    killproc -p $PIDFILE $PROCESS
-    RETVAL=$?
-    echo
-    if [ $RETVAL -eq 0 ]; then
-        rm -f /var/lock/subsys/$SERVICE
-        rm -f $PIDFILE
+force_stop() {
+# Forcefully kill the process
+    [ ! -f "$PIDFILE" ] && return
+    if running ; then
+        kill -15 $pid
+        # Is it really dead?
+        [ -n "$DODTIME" ] && sleep "$DODTIME"s
+        if running ; then
+            kill -9 $pid
+            [ -n "$DODTIME" ] && sleep "$DODTIME"s
+            if running ; then
+                echo "Cannot kill $LABEL (pid=$pid)!"
+                exit 1
+            fi
+        fi
     fi
+    rm -f $PIDFILE
+    return 0
 }
 
-restart() {
-    stop
-    start
-}
-
-reload() {
-    echo -n "Reloading $SERVICE configuration: "
-
-    killproc -p $PIDFILE $PROCESS -USR1
-    RETVAL=$?
-    echo
-    return $RETVAL
-}
-
-# See how we were called.
 case "$1" in
-    start|stop|restart|reload)
-        $1
-        ;;
-    status)
-        status -p $PIDFILE $PROCESS
-        RETVAL=$?
-        ;;
-    force-reload)
-        reload
-        ;;
-    condrestart|try-restart)
-        [ -f /var/lock/subsys/$SERVICE ] && restart || :
-        ;;
-    *)
-        echo "Usage: $0 {start|stop|status|restart|condrestart|reload|force-reload|try-restart}"
-        exit 2
-        ;;
+  start)
+      log_daemon_msg "Starting $DESC" "$NAME"
+      if running ;  then
+          log_progress_msg "already running"
+          log_end_msg 0
+          exit 0
+      fi
+      rm -f $PIDFILE
+      start-stop-daemon --start --quiet --pidfile $PIDFILE \
+			--exec $DAEMON -- -d $VIRTLOCKD_ARGS
+      if running; then
+	  log_end_msg 0
+      else
+	  log_end_msg 1
+      fi
+      ;;
+  stop)
+      log_daemon_msg "Stopping $DESC" "$NAME"
+      if ! running ;  then
+          log_progress_msg "not running"
+          log_end_msg 0
+          exit 0
+      fi
+      start-stop-daemon --stop --quiet --pidfile $PIDFILE \
+			--exec $DAEMON
+      log_end_msg 0
+      ;;
+  force-stop)
+      log_daemon_msg "Forcefully stopping $DESC" "$NAME"
+      force_stop
+      if ! running; then
+	  log_end_msg 0
+      else
+	  log_end_msg 1
+      fi
+      ;;
+  restart)
+      log_daemon_msg "Restarting $DESC" "$DAEMON"
+      start-stop-daemon --oknodo --stop --quiet --pidfile \
+			/var/run/$NAME.pid --exec $DAEMON
+      [ -n "$DODTIME" ] && sleep $DODTIME
+      start-stop-daemon --start --quiet --pidfile \
+			/var/run/$NAME.pid --exec $DAEMON -- -d $libvirtd_opts
+      if running; then
+	  log_end_msg 0
+      else
+	  log_end_msg 1
+      fi
+      ;;
+  reload|force-reload)
+      if running; then
+          log_daemon_msg "Reloading configuration of $DESC" "$NAME"
+	  start-stop-daemon --stop --signal 1 --quiet --pidfile \
+			    /var/run/$NAME.pid --exec $DAEMON
+	  log_end_msg 0
+      else
+          log_warning_msg "libvirt lock manager not running, doing nothing."
+      fi
+      ;;
+  status)
+      log_daemon_msg "Checking status of $DESC" "$NAME"
+      if running ;  then
+          log_progress_msg "running"
+          log_end_msg 0
+      else
+          log_progress_msg "not running"
+          log_end_msg 1
+          if [ -f "$PIDFILE" ] ; then
+              exit 1
+          else
+              exit 3
+          fi
+      fi
+      ;;
+  *)
+      N=/etc/init.d/virtlockd
+      echo "Usage: $N {start|stop|restart|reload|force-reload|status|force-stop}" >&2
+      exit 1
+      ;;
 esac
-exit $RETVAL
+
+exit 0
